### ISSUE TITLE
Example image attributes error

### ISSUE THREAD

**Issue by jamesli2021** [MicroWebStacks/astro-examples#2]
In example 19, the 3rd link threw an error that require width and height attribute attributes.

**Comment by wassfila** [comment]
you mean the getImage


I reproduce it in dev mode I'm looking into that

**Comment by wassfila** [comment]
related issue

- https://github.com/withastro/astro/issues/5202
- https://discord.com/channels/830184174198718474/1042404694112346153

doc reference
- https://docs.astro.build/en/guides/integrations-guide/image/#getimage

But actuall issue was missing import on src of getImage

**Comment by wassfila** [comment]
with 15c2726 it's no error but blank now

**Comment by wassfila** [comment]
now fixed with 260e002
