### ISSUE TITLE
Example is not running

### ISSUE THREAD

**Issue by dhrn** [MicroWebStacks/astro-examples#3]
By the way, Many thanks for the wonderful samples 💯 

**Steps to reproduce**
Try to open the [01 basic ](https://stackblitz.com/github/MicroWebStacks/astro-examples/tree/main/01_basics?file=README.md)in stackblitz & codesandbox, sadly it failes with following error

<img width="1512" alt="image" src="https://github.com/MicroWebStacks/astro-examples/assets/14145706/21ffb221-8518-4055-88bf-99695201e738">

**Comment by wassfila** [comment]
Thanks for pointing this out.
In the first basic sample I intend to test the new beta version of Astro v3 release, unfortunately from one Astro v3 already deprecated node version 16 and from another Stackblitz is using version 16 and according to this https://developer.stackblitz.com/codeflow/codeflow-faq#can-i-change-the-node-version , it is not possible to change it, so for the time being I'll have to drop Stackblitz links in all samples I bump to Astro v3 until Stackblitz move to Node version 18. Note that Node 16 is end of life so it's weird how Stackblizt continue using deprecated version, their problem.

**Comment by wassfila** [comment]
This is now fixed, at least both codesandbox and gitpod are working, gitpod had a config to update
